url = 'https://lenta.ru/news/2019/07/24/shi/'
title_start_tag = '<h1 class="b-topic__title" itemprop="headline">'
title_finish_tag = '</h1><div class="b-topic__socials _header">'
text_start_tag = '<div class="b-text clearfix js-topic__text" itemprop="articleBody">'
text_finish_tag = '</p><div class="b-box">'